name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build & test
        run: mvn clean verify jacoco:report
      - name: Check jacoco.xml exists
        run: |
          if [ ! -f target/site/jacoco/jacoco.xml ]; then
            echo "Brak pliku jacoco.xml! Sprawdź konfigurację Jacoco i testy."
            exit 1
          fi
      - name: Check coverage
        run: |
          MISSED=$(awk -F'"' '/counter type="INSTRUCTION"/ {for(i=1;i<=NF;i++){if($i~/missed=/){m=$(i+1)}}} END {print m}' target/site/jacoco/jacoco.xml)
          COVERED=$(awk -F'"' '/counter type="INSTRUCTION"/ {for(i=1;i<=NF;i++){if($i~/covered=/){c=$(i+1)}}} END {print c}' target/site/jacoco/jacoco.xml)
          TOTAL=$((MISSED + COVERED))
          if [ "$TOTAL" -eq 0 ]; then
            echo "Brak danych o pokryciu! Sprawdź czy plik jacoco.xml istnieje."
            exit 1
          fi
          COVERAGE=$(echo "scale=2; ($COVERED / $TOTAL) * 100" | bc)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
            echo "Coverage too low!"
            exit 1
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml