name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build & test
        run: mvn clean verify
      - name: Check coverage
        run: |
          MISSED=$(awk -F'"' '/counter type="INSTRUCTION"/ {print $4; exit}' target/site/jacoco/jacoco.xml)
          COVERED=$(awk -F'"' '/counter type="INSTRUCTION"/ {print $6; exit}' target/site/jacoco/jacoco.xml)
          TOTAL=$((MISSED + COVERED))
          COVERAGE=$(echo "scale=2; ($COVERED / $TOTAL) * 100" | bc)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
            echo "Coverage too low!"
            exit 1
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml